site_name: 简说基因
site_url: https://jianzuoyi.github.io/
site_author: Zuoyi Jian
site_description: >-
    肿瘤基因检测/病原微生物基因检测/无创产前诊断。


# Repository
repo_name: jianzuoyi.github.io
repo_url: https://github.com/jianzuoyi/jianzuoyi.github.io
edit_url:
zhihu_url: https://www.zhihu.com/people/jianzuoyi
ncbi_url: https://www.ncbi.nlm.nih.gov/

# Copyright
copyright: Copyright &copy; 2019 - 2020 Zuoyi Jian

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        extensions/admonition.md: reference/admonitions.md
        extensions/codehilite.md: reference/code-blocks.md
        extensions/footnotes.md: reference/footnotes.md
        extensions/metadata.md: reference/meta-tags.md
        extensions/permalinks.md: setup/setting-up-navigation.md #permalink
        extensions/pymdown.md: reference/admonitions.md
        plugins/search.md: setup/setting-up-site-search.md
        plugins/revision-date.md: setup/adding-a-git-repository.md #revision-date
        releases/4.md: upgrading.md #upgrading-from-4x-to-5x
        releases/5.md: upgrading.md #upgrading-from-3x-to-4x
        releases/changelog.md: changelog.md
        sponsorship.md: insiders.md
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jianzuoyi
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/jianzuoyi/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/jianzuoyi/mkdocs-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jianzuoyi
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jianzuoyi/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/jianzuoyi

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.abbr
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: jianzuoyi
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

# Page tree
nav:
  - 主页: index.md
  - 日志:
    - 2020-11-20 为什么说生物信息学是真正的大数据行业？: 2020-11-20-base-pair-unit.md
    - 2020-11-17 生物信息基础：基因组文件读写（pysam）: 2020-11-17-pysam.md
    - 2020-11-16 一文搞懂NCBI Blast本地数据库（NT/NR等）构建: 2020-11-16-local-ncbi-db.md
    - 2020-11-14 生物信息学中重要的评估竞赛: 2020-11-14-bioinfo-competition.md
    - 2020-11-14 在线学习的十条规则: 2020-11-14-online-learning.md
    - 2020-11-13 生物信息学：全景: 2020-11-13-bioinfo-full-view.md
    - 2020-11-12 谈一谈如何实现一个小目标: 2020-11-13-think-like-company.md
    - 2020-11-12 《基因大数据智能生产及分析》笔记: 2020-11-12-gene-bigdata-jiyinhui.md
    - 2020-11-10 学生信难吗？我给读者的回信: 2020-11-10.letter-to-reader-bioinfo.md
    - 1.一个生信人的自白：从生物转生信，我的学习与工作经历: 1.aboutme.md
    - 2.重拾写作：从开始到放弃: 2.markdown.md
    - 3.生物信息基础：SSH应用，如何优雅地登录远程服务器？: 3.ssh.md
    - 4.奔涌吧，生信: 4.houlang.md
    - 5.教学相长：愿我们都不忘初心，有始有终: 5.chuxin.md
    - 6.最佳生物信息工作环境: 6.best-bioinfo-env-mac.md
    - 7.强烈推荐Windows平台下生信环境搭配：Windows Terminal + WSL: 7.best-bioinfo-env-win.md
    - 8.（一）概述：NGS测序在病原微生物检测中的应用: 8.ngs-and-micro.md
    - 9.病原微生物扩增子数据分析实战（一）：bcl2fastq软件完成数据拆分: 9.microbe-bcl2fastq.md
    - 10.病原微生物扩增子数据分析实战（二）：fastp软件进行质量控制: 10.microbe-fastp.md
    - 11.病原微生物扩增子数据分析实战（三）：vsearch软件鉴定物种组成: 11.microbe-vsearch.md
    - 12.Aspera：基因组数据高速下载利器，以NCBI和EBI数据下载为例: 12.aspera.md
  - 自学生信:
    - 如何自学生物信息学：从菜鸟到专家: 2020-11-23-learn-bioinfomatics.md
  - Linux教程:
    - Linux命令速查手册: tutorial/tutorial-linux.md
  - Conda教程:
    - Conda教程: tutorial/tutorial-conda.md
  - Git教程:
    - Git教程: tutorial/tutorial-git.md
